

MAPS = {
    "ascent": [
        "Game/Maps/Ascent/Ascent_Art_A.umap",
        # "Game/Maps/Ascent/Ascent_Art_APathMid.umap",
        # "Game/Maps/Ascent/Ascent_Art_Atk.umap",
        # "Game/Maps/Ascent/Ascent_Art_AtkPathA.umap",
        # "Game/Maps/Ascent/Ascent_Art_AtkPathB.umap",
        # "Game/Maps/Ascent/Ascent_Art_B.umap",
        # "Game/Maps/Ascent/Ascent_Art_Def.umap",
        # "Game/Maps/Ascent/Ascent_Art_DefPathA.umap",
        # "Game/Maps/Ascent/Ascent_Art_DefPathB.umap",
        # "Game/Maps/Ascent/Ascent_Art_Env_VFX.umap",
        # "Game/Maps/Ascent/Ascent_Art_Mid.umap",
        # "Game/Maps/Ascent/Ascent_Art_Vista.umap",
        # "Game/Maps/Ascent/Ascent_Art_VistaA.umap",
        # "Game/Maps/Ascent/Ascent_Art_VistaAtk.umap",
        # "Game/Maps/Ascent/Ascent_Art_VistaB.umap",
        # "Game/Maps/Ascent/Ascent_Art_VistaDef.umap",
        # "Game/Maps/Ascent/Ascent_Lighting.umap"
    ],
    "split": [
        "Game/Maps/Bonsai/Bonsai_Art_A.umap",
        "Game/Maps/Bonsai/Bonsai_Art_AtkPathA.umap",
        "Game/Maps/Bonsai/Bonsai_Art_AtkPathB.umap",
        "Game/Maps/Bonsai/Bonsai_Art_AtkSpawn.umap",
        "Game/Maps/Bonsai/Bonsai_Art_ATower.umap",
        "Game/Maps/Bonsai/Bonsai_Art_B.umap",
        "Game/Maps/Bonsai/Bonsai_Art_BTower.umap",
        "Game/Maps/Bonsai/Bonsai_Art_DefPathA.umap",
        "Game/Maps/Bonsai/Bonsai_Art_DefPathB.umap",
        "Game/Maps/Bonsai/Bonsai_Art_DefSpawn.umap",
        "Game/Maps/Bonsai/Bonsai_Art_Mid.umap",
        "Game/Maps/Bonsai/Bonsai_Art_MidConstruction.umap",
        "Game/Maps/Bonsai/Bonsai_Art_MidVent.umap",
        "Game/Maps/Bonsai/Bonsai_Art_Sewer.umap",
        "Game/Maps/Bonsai/Bonsai_Art_VistaA.umap",
        "Game/Maps/Bonsai/Bonsai_Art_VistaAtk.umap",
        "Game/Maps/Bonsai/Bonsai_Art_VistaB.umap",
        "Game/Maps/Bonsai/Bonsai_Art_VistaDef.umap",
        "Game/Maps/Bonsai/Bonsai_Lighting.umap",
        "Game/Maps/Bonsai/Bonsai_VFX.umap"
    ],
    "bind": [
        "Game/Maps/Duality/Duality_Art_A.umap",
        # "Game/Maps/Duality/Duality_Art_Atk.umap",
        # "Game/Maps/Duality/Duality_Art_AtkPathA.umap",
        # "Game/Maps/Duality/Duality_Art_AtkPathB.umap",
        # "Game/Maps/Duality/Duality_Art_B.umap",
        # "Game/Maps/Duality/Duality_Art_BathHouse.umap",
        # "Game/Maps/Duality/Duality_Art_Def.umap",
        # "Game/Maps/Duality/Duality_Art_DefPathA.umap",
        # "Game/Maps/Duality/Duality_Art_DefPathB.umap",
        # "Game/Maps/Duality/Duality_Art_Destructibles.umap",
        # "Game/Maps/Duality/Duality_Art_Lantern.umap",
        # "Game/Maps/Duality/Duality_Art_Mid.umap",
        # "Game/Maps/Duality/Duality_Art_MidPathA.umap",
        # "Game/Maps/Duality/Duality_Art_MIdPathB.umap",
        # "Game/Maps/Duality/Duality_Art_Signage.umap",
        # "Game/Maps/Duality/Duality_Art_TPArrivalRooms.umap",
        # "Game/Maps/Duality/Duality_Art_Vista.umap",
        # "Game/Maps/Duality/Duality_Lighting.umap",
        # "Game/Maps/Duality/Duality_VFX.umap"
    ],
    "icebox": [
        "Game/Maps/Port/Port_Art_A.umap",
        "Game/Maps/Port/Port_Art_AtkPathB.umap",
        "Game/Maps/Port/Port_Art_AtkSpawn.umap",
        "Game/Maps/Port/Port_Art_B.umap",
        "Game/Maps/Port/Port_Art_DefPathB.umap",
        "Game/Maps/Port/Port_Art_DefSpawn.umap",
        "Game/Maps/Port/Port_Art_Mid.umap",
        "Game/Maps/Port/Port_Art_SnowAll.umap",
        "Game/Maps/Port/Port_Art_VFX.umap",
        "Game/Maps/Port/Port_Art_Vista.umap",
        "Game/Maps/Port/Port_Art_VistaA.umap",
        "Game/Maps/Port/Port_Art_VistaB.umap",
        "Game/Maps/Port/Port_Lighting.umap"
    ],
    "breeze": [
        "Game/Maps/Foxtrot/Foxtrot_Art_A.umap",
        "Game/Maps/Foxtrot/Foxtrot_Art_A_Tunnel.umap",
        "Game/Maps/Foxtrot/Foxtrot_Art_AtkPath_A.umap",
        "Game/Maps/Foxtrot/Foxtrot_Art_AtkPath_B.umap",
        "Game/Maps/Foxtrot/Foxtrot_Art_AtkSpawn.umap",
        "Game/Maps/Foxtrot/Foxtrot_Art_B.umap",
        "Game/Maps/Foxtrot/Foxtrot_Art_DefPath_B.umap",
        "Game/Maps/Foxtrot/Foxtrot_Art_DefPath_Mid.umap",
        "Game/Maps/Foxtrot/Foxtrot_Art_DefSpawn.umap",
        "Game/Maps/Foxtrot/Foxtrot_Art_Mid.umap",
        "Game/Maps/Foxtrot/Foxtrot_Art_MidLower.umap",
        "Game/Maps/Foxtrot/Foxtrot_Art_MidUpper.umap",
        "Game/Maps/Foxtrot/Foxtrot_Art_VFX.umap",
        "Game/Maps/Foxtrot/Foxtrot_Art_Vista.umap",
        "Game/Maps/Foxtrot/Foxtrot_Art_VistaShip.umap",
        "Game/Maps/Foxtrot/Foxtrot_Art_Workshop.umap",
        "Game/Maps/Foxtrot/Foxtrot_Lighting.umap"
    ],
    "haven": [
        "Game/Maps/Triad/Triad_Alt5.umap",
        "Game/Maps/Triad/Triad_Art_A.umap",
        "Game/Maps/Triad/Triad_Art_Atk.umap",
        "Game/Maps/Triad/Triad_Art_AtkPathA.umap",
        "Game/Maps/Triad/Triad_Art_AtkPathB.umap",
        "Game/Maps/Triad/Triad_Art_AtkPathC.umap",
        "Game/Maps/Triad/Triad_Art_B.umap",
        "Game/Maps/Triad/Triad_Art_Basalt.umap",
        "Game/Maps/Triad/Triad_Art_C.umap",
        "Game/Maps/Triad/Triad_Art_C_Destruction.umap",
        "Game/Maps/Triad/Triad_Art_Def.umap",
        "Game/Maps/Triad/Triad_Art_Destruction.umap",
        "Game/Maps/Triad/Triad_Art_Vista_Destruction.umap",
        "Game/Maps/Triad/Triad_Art_Working.umap",
        "Game/Maps/Triad/Triad_LightingDestruction.umap",
        "Game/Maps/Triad/Triad_VFX_Destruction.umap"
    ],
    "menu": [
        "Game/Maps/Menu/MainMenu_Ep02_01_Characters.umap",
        "Game/Maps/Menu/MainMenu_Ep02_01_EnvArt.umap",
        "Game/Maps/Menu/MainMenu_Ep02_01_Lighting.umap",
        "Game/Maps/Menu/MainMenuV2.umap"
    ],
    "poveglia": [
        "Game/Maps/Poveglia/Range_Art_AsylumDown_ClientOnly_CosmeticDetails.umap",
        "Game/Maps/Poveglia/Range_Art_AsylumDown.umap",
        "Game/Maps/Poveglia/Range_Art_AsylumUp_ClientOnly_CosmeticDetails.umap",
        "Game/Maps/Poveglia/Range_Art_AsylumUp.umap",
        "Game/Maps/Poveglia/Range_Art_BMainInterior_ClientOnly_CosmeticDetails.umap",
        "Game/Maps/Poveglia/Range_Art_BMainInterior.umap",
        "Game/Maps/Poveglia/Range_Art_Boathouse_ClientOnly_CosmeticDetails.umap",
        "Game/Maps/Poveglia/Range_Art_Boathouse_hide.umap",
        "Game/Maps/Poveglia/Range_Art_Boathouse.umap",
        "Game/Maps/Poveglia/Range_Art_Bombsite_ClientOnly_CosmeticDetails.umap",
        "Game/Maps/Poveglia/Range_Art_Bombsite.umap",
        "Game/Maps/Poveglia/Range_Art_Bridge_ClientOnly_CosmeticDetails.umap",
        "Game/Maps/Poveglia/Range_Art_Bridge.umap",
        "Game/Maps/Poveglia/Range_Art_Cemetery_ClientOnly_CosmeticDetails.umap",
        "Game/Maps/Poveglia/Range_Art_Cemetery.umap",
        "Game/Maps/Poveglia/Range_Art_Gallery_ClientOnly_CosmeticDetails.umap",
        "Game/Maps/Poveglia/Range_Art_Gallery.umap",
        "Game/Maps/Poveglia/Range_Art_Hospital_ClientOnly_CosmeticDetails.umap",
        "Game/Maps/Poveglia/Range_Art_Hospital.umap",
        "Game/Maps/Poveglia/Range_Art_JumpCourse_ClientOnly_CosmeticDetails.umap",
        "Game/Maps/Poveglia/Range_Art_JumpCourse_Outdated.umap",
        "Game/Maps/Poveglia/Range_Art_JumpCourse.umap",
        "Game/Maps/Poveglia/Range_Art_Tower_ClientOnly_CosmeticDetails.umap",
        "Game/Maps/Poveglia/Range_Art_Tower.umap",
        "Game/Maps/Poveglia/Range_Art_Vegetation_ClientOnly_CosmeticDetails.umap",
        "Game/Maps/Poveglia/Range_Art_Vegetation.umap",
        "Game/Maps/Poveglia/Range_Art_Vista_ClientOnly_CosmeticDetails.umap",
        "Game/Maps/Poveglia/Range_Art_Vista.umap",
        "Game/Maps/Poveglia/Range_Art_VTOL_ClientOnly_CosmeticDetails.umap",
        "Game/Maps/Poveglia/Range_Art_VTOL.umap",
        "Game/Maps/Poveglia/Range_Audio_Spatial.umap",
        "Game/Maps/Poveglia/Range_BVPawn.umap",
        "Game/Maps/Poveglia/Range_BVProjectile.umap",
        "Game/Maps/Poveglia/Range_ClientOnly.umap",
        "Game/Maps/Poveglia/Range_Gameplay.umap",
        "Game/Maps/Poveglia/Range_Greybox+Jump_Reference.umap",
        "Game/Maps/Poveglia/Range_Lighting.umap",
        "Game/Maps/Poveglia/Range_Navmesh.umap",
        "Game/Maps/Poveglia/Range_NPE_Only_Gameplay.umap",
        "Game/Maps/Poveglia/Range_Only_Gameplay.umap",
        "Game/Maps/Poveglia/Range_VFX.umap",
        "Game/Maps/Poveglia/Range.umap",
    ]}
